# Generated by Django 4.2.20 on 2026-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_order_delivery_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, help_text='Estimated time when order will be ready for pickup/delivery', null=True),
        ),
    ]
