# Generated by Django 4.2.20 on 2026-01-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_estimated_ready_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uid',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
