# Generated by Django 4.2.20 on 2026-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Ready', 'Ready for Pickup'), ('PickedUp', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Confirmed', max_length=50),
        ),
    ]
