# Generated by Django 4.2.20 on 2026-01-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_favoriteproductservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_order_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for refund request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, help_text='Reason for denial if denied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who approved or denied the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refund_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='auth_api.customer')),
            ],
            options={
                'verbose_name': 'Refund Request',
                'verbose_name_plural': 'Refund Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='orders_refu_order_i_58e915_idx'), models.Index(fields=['requested_by', 'status'], name='orders_refu_request_c94179_idx'), models.Index(fields=['status', 'created_at'], name='orders_refu_status_089089_idx')],
            },
        ),
    ]
