# Generated by Django 4.2.20 on 2025-12-12 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('user', models.OneToOneField(help_text='User this permissions record belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_view_own_vendor_profile', models.BooleanField(default=False, help_text='Can view own vendor profile')),
                ('can_edit_own_vendor_profile', models.BooleanField(default=False, help_text='Can edit own vendor profile')),
                ('can_view_own_vendor_orders', models.BooleanField(default=False, help_text='Can view own vendor orders')),
                ('can_update_order_status', models.BooleanField(default=False, help_text='Can update order status')),
                ('can_view_own_vendor_earnings', models.BooleanField(default=False, help_text='Can view own vendor earnings')),
                ('can_manage_vendor_menu', models.BooleanField(default=False, help_text='Can manage vendor menu items')),
                ('can_view_vendor_analytics', models.BooleanField(default=False, help_text='Can view vendor analytics')),
                ('can_view_own_customer_profile', models.BooleanField(default=False, help_text='Can view own customer profile')),
                ('can_edit_own_customer_profile', models.BooleanField(default=False, help_text='Can edit own customer profile')),
                ('can_view_own_customer_orders', models.BooleanField(default=False, help_text='Can view own customer orders')),
                ('can_create_orders', models.BooleanField(default=False, help_text='Can create orders')),
                ('can_cancel_orders', models.BooleanField(default=False, help_text='Can cancel orders')),
                ('can_view_order_history', models.BooleanField(default=False, help_text='Can view order history')),
                ('can_rate_orders', models.BooleanField(default=False, help_text='Can rate orders')),
                ('can_make_payments', models.BooleanField(default=False, help_text='Can make payments')),
                ('can_view_own_payments', models.BooleanField(default=False, help_text='Can view own payments')),
                ('can_view_all_payments', models.BooleanField(default=False, help_text='Can view all payments (admin)')),
                ('can_process_refunds', models.BooleanField(default=False, help_text='Can process refunds')),
                ('can_view_all_orders', models.BooleanField(default=False, help_text='Can view all orders (admin)')),
                ('can_manage_orders', models.BooleanField(default=False, help_text='Can manage all orders (admin)')),
                ('can_perform_sync', models.BooleanField(default=False, help_text='Can perform data synchronization')),
                ('can_resolve_sync_conflicts', models.BooleanField(default=False, help_text='Can resolve sync conflicts')),
                ('can_view_sync_status', models.BooleanField(default=False, help_text='Can view sync status')),
                ('can_update_location', models.BooleanField(default=False, help_text='Can update delivery location')),
                ('can_view_order_tracking', models.BooleanField(default=False, help_text='Can view order tracking')),
                ('can_manage_deliveries', models.BooleanField(default=False, help_text='Can manage deliveries (admin)')),
                ('can_view_all_vendors', models.BooleanField(default=False, help_text='Can view all vendors (admin)')),
                ('can_manage_vendors', models.BooleanField(default=False, help_text='Can manage vendors (admin)')),
                ('can_view_all_customers', models.BooleanField(default=False, help_text='Can view all customers (admin)')),
                ('can_manage_customers', models.BooleanField(default=False, help_text='Can manage customers (admin)')),
                ('can_view_audit_logs', models.BooleanField(default=False, help_text='Can view audit logs')),
                ('can_manage_system_settings', models.BooleanField(default=False, help_text='Can manage system settings')),
                ('can_create_offline_orders', models.BooleanField(default=False, help_text='Can create orders offline')),
                ('can_view_offline_orders', models.BooleanField(default=False, help_text='Can view offline orders')),
                ('can_record_offline_payments', models.BooleanField(default=False, help_text='Can record offline payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Permissions',
                'verbose_name_plural': 'User Permissions',
            },
        ),
    ]
