# Generated by Django 4.2.20 on 2025-12-12 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0002_userpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(help_text='User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number", max_length=15, null=True)),
                ('country_code', models.CharField(blank=True, help_text='Country calling code (e.g., +1, +27)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this address belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='auth_api_ad_user_id_84fd40_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text="User's country", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='lookups.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_address',
            field=models.ForeignKey(blank=True, help_text="User's primary address", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_address_users', to='auth_api.address'),
        ),
    ]
