# Generated by Django 4.2.20 on 2025-12-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('auth_api', '0003_userprofile_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Languages the user speaks/understands', related_name='users', to='lookups.language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_language',
            field=models.ForeignKey(blank=True, help_text="User's primary/preferred language", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_language_users', to='lookups.language'),
        ),
    ]
