# Generated by Django 4.2.20 on 2025-12-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_email_auth_2fa_oauth'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='auth_api_oa_provide_d000f6_idx',
            old_name='auth_api_oauth_provider_id',
        ),
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='auth_api_oa_user_id_b36744_idx',
            old_name='auth_api_oauth_user_provider',
        ),
        migrations.RenameIndex(
            model_name='oauthaccount',
            new_name='auth_api_oa_email_03ae18_idx',
            old_name='auth_api_oauth_email',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='auth_api_ot_user_id_ecae2b_idx',
            old_name='auth_api_otp_user_used_exp',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='auth_api_ot_session_25ac6f_idx',
            old_name='auth_api_otp_session_token',
        ),
        migrations.AddField(
            model_name='userdocument',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for the document (e.g., OAuth profile picture)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded file', null=True, upload_to='user_documents/'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(blank=True, choices=[('id_document', 'ID Document'), ('proof_of_address', 'Proof of Address'), ('profile_picture', 'Profile Picture'), ('other', 'Other'), ('proof_of_account', 'Proof of Account')], max_length=100, null=True),
        ),
    ]
