# Generated by Django 4.2.20 on 2025-12-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('auth_api', '0006_rename_auth_api_oauth_provider_id_auth_api_oa_provide_d000f6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country for this address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='lookups.country'),
        ),
    ]
