# Generated by Django 4.2.20 on 2026-01-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorimage_productimage_and_more'),
        ('auth_api', '0007_remove_country_from_profile_add_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default delivery address?'),
        ),
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vendors', to='auth_api.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Favorite Vendor',
                'verbose_name_plural': 'Favorite Vendors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='auth_api_fa_custome_67548f_idx')],
                'unique_together': {('customer', 'vendor')},
            },
        ),
    ]
