# Generated by Django 4.2.20 on 2026-01-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorimage_productimage_and_more'),
        ('auth_api', '0008_address_is_default_favoritevendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProductService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='auth_api.customer')),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vendors.productservice')),
            ],
            options={
                'verbose_name': 'Favorite Product/Service',
                'verbose_name_plural': 'Favorite Products/Services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='auth_api_fa_custome_49abff_idx')],
                'unique_together': {('customer', 'product_service')},
            },
        ),
    ]
