# Generated by Django 4.2.20 on 2025-12-12 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(max_length=100)),
                ('action_name', models.CharField(blank=True, max_length=50, null=True)),
                ('table_name', models.CharField(max_length=100)),
                ('row_id', models.IntegerField(help_text='Primary key of the row affected')),
                ('data_payload', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, help_text='Actor who initiated the change (Nullable for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['event_time'], name='audit_audit_event_t_483f39_idx'), models.Index(fields=['user', 'event_time'], name='audit_audit_user_id_3e9308_idx'), models.Index(fields=['table_name', 'row_id'], name='audit_audit_table_n_16f95d_idx'), models.Index(fields=['service_name', 'action_name'], name='audit_audit_service_b35108_idx')],
            },
        ),
    ]
