# Generated by Django 4.2.20 on 2025-12-12 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('total_operations', models.PositiveIntegerField(default=0)),
                ('successful_operations', models.PositiveIntegerField(default=0)),
                ('failed_operations', models.PositiveIntegerField(default=0)),
                ('conflicts_resolved', models.PositiveIntegerField(default=0)),
                ('connection_type', models.CharField(blank=True, max_length=20)),
                ('bandwidth_used', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Session',
                'verbose_name_plural': 'Sync Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('model_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('vendor', 'Vendor'), ('menu_item', 'Menu Item'), ('review', 'Review'), ('user', 'User')], max_length=20)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('server_id', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField()),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_data', models.JSONField()),
                ('server_data', models.JSONField()),
                ('conflict_field', models.CharField(blank=True, max_length=100)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('resolution_strategy', models.CharField(choices=[('server_wins', 'Server Wins'), ('client_wins', 'Client Wins'), ('manual', 'Manual Resolution'), ('merge', 'Merge')], default='manual', max_length=20)),
                ('resolved_data', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sync_queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncqueue')),
            ],
            options={
                'verbose_name': 'Sync Conflict',
                'verbose_name_plural': 'Sync Conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_interval', models.PositiveIntegerField(default=300)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay', models.PositiveIntegerField(default=60)),
                ('default_conflict_strategy', models.CharField(choices=[('server_wins', 'Server Wins'), ('client_wins', 'Client Wins'), ('manual', 'Manual Resolution'), ('merge', 'Merge')], default='manual', max_length=20)),
                ('sync_history_retention_days', models.PositiveIntegerField(default=30)),
                ('snapshot_retention_days', models.PositiveIntegerField(default=7)),
                ('sync_on_wifi_only', models.BooleanField(default=False)),
                ('max_bandwidth_per_sync', models.PositiveIntegerField(default=10485760)),
                ('notify_on_sync_completion', models.BooleanField(default=True)),
                ('notify_on_conflicts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Configuration',
                'verbose_name_plural': 'Sync Configurations',
            },
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('vendor', 'Vendor'), ('menu_item', 'Menu Item'), ('review', 'Review'), ('user', 'User')], max_length=20)),
                ('record_id', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Snapshot',
                'verbose_name_plural': 'Data Snapshots',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'model_type', 'record_id', 'version')},
            },
        ),
    ]
