# Generated by Django 4.2.20 on 2026-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
    ]
