# Generated by Django 4.2.20 on 2026-01-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_productservice_image_vendor_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vendor_profiles/')),
                ('is_preview', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Image',
                'verbose_name_plural': 'Vendor Images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_preview', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.productservice')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preview', True)), fields=('vendor', 'is_preview'), name='unique_preview_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preview', True)), fields=('product_service', 'is_preview'), name='unique_preview_per_product'),
        ),
    ]
