# Generated by Django 4.2.20 on 2026-01-10 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorimage_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='available_for',
            field=models.CharField(choices=[('delivery', 'Delivery Only'), ('pickup', 'Pickup Only'), ('both', 'Both Delivery and Pickup')], default='both', help_text='Whether this item is available for delivery, pickup, or both', max_length=10),
        ),
        migrations.AddField(
            model_name='productservice',
            name='estimated_preparation_time_minutes',
            field=models.IntegerField(blank=True, help_text='Estimated preparation time in minutes (used as default for orders)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
