# Generated by Django 4.2.20 on 2025-12-12 21:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_alpha2', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., US, CA)', max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(help_text='Official country name (e.g., United States of America)', max_length=100)),
                ('iso_alpha3', models.CharField(help_text='ISO 3166-1 alpha-3 code (e.g., USA, CAN)', max_length=3, unique=True)),
                ('iso_numeric', models.CharField(help_text='ISO 3166-1 numeric code (e.g., 840, 124)', max_length=3, unique=True)),
                ('region', models.CharField(blank=True, help_text='World Bank/UN major region (e.g., Americas, Europe)', max_length=50, null=True)),
                ('sub_region', models.CharField(blank=True, help_text='More granular region (e.g., Northern America)', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Country centroid latitude for mapping', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Country centroid longitude for mapping', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calling_code', models.CharField(help_text='International telephone code (e.g., 1, 44)', max_length=10)),
                ('tld', models.CharField(help_text='Top-level domain (e.g., .us, .ca)', max_length=5, unique=True)),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, CAD)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country Codes',
                'verbose_name_plural': 'Country Codes',
                'ordering': ['country__country_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryFlags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag_svg_url', models.CharField(help_text='URL to the high-resolution SVG flag file', max_length=255)),
                ('flag_png_64', models.CharField(help_text='URL to a common 64px PNG flag file (for lists/mobile)', max_length=255)),
                ('flag_emoji', models.CharField(blank=True, help_text='Unicode/Emoji representation of the flag (e.g., 🇺🇸)', max_length=4, null=True)),
                ('flag_alt_text', models.CharField(blank=True, help_text='Alternative text describing the flag for accessibility', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country Flags',
                'verbose_name_plural': 'Country Flags',
                'ordering': ['country__country_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_official', models.BooleanField(default=False, help_text='True if the language is an official language of the country')),
                ('is_primary', models.BooleanField(default=False, help_text='True if this is the most common language spoken by the population')),
                ('percentage_of_speakers', models.DecimalField(blank=True, decimal_places=2, help_text="Percentage of the country's population that speaks this language", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(blank=True, choices=[('official', 'Official'), ('de_facto_national', 'De Facto National'), ('regional', 'Regional'), ('minority', 'Minority'), ('recognized', 'Recognized'), ('working', 'Working')], help_text='Detailed status (e.g., de facto national, minority, regional)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country Language',
                'verbose_name_plural': 'Country Languages',
                'ordering': ['country__country_name', '-is_primary', '-is_official', 'language__language_name_en'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, ZAR)', max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Currency symbol (e.g., $, €, R)', max_length=10, null=True)),
                ('numeric_code', models.CharField(blank=True, help_text='ISO 4217 numeric code', max_length=3, null=True, unique=True)),
                ('decimal_places', models.IntegerField(default=2, help_text='Number of decimal places')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso_639_1', models.CharField(help_text='ISO 639-1 code (2-letter code, e.g., en, es, fr)', max_length=2, primary_key=True, serialize=False)),
                ('language_name_en', models.CharField(help_text='Language name in English (e.g., Spanish)', max_length=50)),
                ('native_name', models.CharField(help_text='Language name as written in that language (e.g., Español)', max_length=100)),
                ('iso_639_2', models.CharField(help_text='ISO 639-2 code (3-letter code, e.g., spa)', max_length=3, unique=True)),
                ('type', models.CharField(choices=[('living', 'Living'), ('extinct', 'Extinct'), ('ancient', 'Ancient'), ('constructed', 'Constructed'), ('historical', 'Historical')], help_text='Classification (e.g., living, extinct, ancient)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['language_name_en'],
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Timezone name (e.g., Africa/Johannesburg)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable timezone name', max_length=200)),
                ('offset_hours', models.IntegerField(help_text='UTC offset in hours')),
                ('offset_minutes', models.IntegerField(default=0, help_text='Additional UTC offset in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
                'ordering': ['offset_hours', 'offset_minutes', 'name'],
                'indexes': [models.Index(fields=['name'], name='lookups_tim_name_0125d4_idx'), models.Index(fields=['is_active'], name='lookups_tim_is_acti_0c3203_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguageScripts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('script_code', models.CharField(help_text='ISO 15924 script code (e.g., Latn, Cyrl, Arab)', max_length=4)),
                ('script_name', models.CharField(help_text='Name of the script (e.g., Latin, Cyrillic)', max_length=50)),
                ('is_rtl', models.BooleanField(default=False, help_text='True if the script is written Right-to-Left (e.g., Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='lookups.language')),
            ],
            options={
                'verbose_name': 'Language Script',
                'verbose_name_plural': 'Language Scripts',
                'ordering': ['language__language_name_en', 'script_name'],
            },
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['iso_639_1'], name='lookups_lan_iso_639_41380d_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['iso_639_2'], name='lookups_lan_iso_639_3fd43b_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['type'], name='lookups_lan_type_7c321d_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_active'], name='lookups_lan_is_acti_2ed883_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='lookups_cur_code_d64079_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='lookups_cur_is_acti_233590_idx'),
        ),
        migrations.AddField(
            model_name='countrylanguages',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='lookups.country'),
        ),
        migrations.AddField(
            model_name='countrylanguages',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='lookups.language'),
        ),
        migrations.AddField(
            model_name='countryflags',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='lookups.country'),
        ),
        migrations.AddField(
            model_name='countrycodes',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='lookups.country'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_alpha2'], name='lookups_cou_iso_alp_4133a1_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_alpha3'], name='lookups_cou_iso_alp_b314a0_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_numeric'], name='lookups_cou_iso_num_d32202_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region', 'sub_region'], name='lookups_cou_region_b0516b_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['is_active'], name='lookups_cou_is_acti_2b3233_idx'),
        ),
        migrations.AddIndex(
            model_name='languagescripts',
            index=models.Index(fields=['language', 'script_code'], name='lookups_lan_languag_f595c5_idx'),
        ),
        migrations.AddIndex(
            model_name='languagescripts',
            index=models.Index(fields=['is_rtl'], name='lookups_lan_is_rtl_882991_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='languagescripts',
            unique_together={('language', 'script_code')},
        ),
        migrations.AddIndex(
            model_name='countrylanguages',
            index=models.Index(fields=['country', 'language'], name='lookups_cou_country_977040_idx'),
        ),
        migrations.AddIndex(
            model_name='countrylanguages',
            index=models.Index(fields=['is_official'], name='lookups_cou_is_offi_983fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='countrylanguages',
            index=models.Index(fields=['is_primary'], name='lookups_cou_is_prim_ec8591_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='countrylanguages',
            unique_together={('country', 'language')},
        ),
        migrations.AddIndex(
            model_name='countrycodes',
            index=models.Index(fields=['calling_code'], name='lookups_cou_calling_6e9fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='countrycodes',
            index=models.Index(fields=['tld'], name='lookups_cou_tld_b9fd58_idx'),
        ),
        migrations.AddIndex(
            model_name='countrycodes',
            index=models.Index(fields=['currency_code'], name='lookups_cou_currenc_9d5bc0_idx'),
        ),
    ]
